### ISSUE TITLE
Incorrect placemant of highlights

### ISSUE THREAD

**Issue by Nogostradamus** [jwarby/jquery-pagewalkthrough#63]
I have an issue with hole position. See img attached.
![highlight](https://cloud.githubusercontent.com/assets/11678754/6898533/af6b7de4-d6f2-11e4-8a45-91e2259685e7.png)
I have fixed that. Instead of:
        .height(Math.min(maxHeight, targetElement.outerHeight()))
        .width(targetElement.outerWidth())
        .css({
            top: targetElement.offset().top - 20, // top/left minus padding
            left: targetElement.offset().left - 20,
        })
I have used:
        .height(Math.min(maxHeight, targetElement.outerHeight())+ 20)
        .width(targetElement.outerWidth()+20)
        .css({
            top: targetElement.offset().top -10, // top/left minus padding
            left: targetElement.offset().left-10,
        }) 
I have added extra 20 to Height and width so offset take half of it back to center around the target,
And after it looks like that: 
![highlight2](https://cloud.githubusercontent.com/assets/11678754/6898966/48ccdc24-d6f5-11e4-8655-046fdf1950c0.png)
It's bigger so all element can be seen and it fits the target better.

**Comment by nenadelite** [comment]
Hi

I have a same issue with tooltip positioning.

Now is:

.css({
             // Recommended to be at least twice the inset box-shadow spread
            padding: '20px',
            position: 'absolute',
            top: targetElement.offset().top - 20, // top/left minus padding
            left: targetElement.offset().left - 20

For my situation, that part of code should be:

            top: targetElement.offset().top, // top/left minus padding
            left: targetElement.offset().left



I've just removed additional 20 to offset on top and left and works fine by me.
