### ISSUE TITLE
How can I run a function before a step?

### ISSUE THREAD

**Issue by zhangyuan0532** [jwarby/jquery-pagewalkthrough#72]
I want to call a function before a step.
For example show a tab, show a modal and so on.

It would be better if it could call function after step for close the modal.

How can I do this?

**Comment by jwarby** [comment]
Hi, check the docs here: https://github.com/jwarby/jquery-pagewalkthrough#jquery-page-walkthrough-default-options

You can add `onEnter` and `onLeave` callbacks for each step.

Hope this helps!

**Comment by zhangyuan0532** [comment]
Thanks.
