### ISSUE TITLE
Need options for mapping keys to methods

### ISSUE THREAD

**Issue by NamdhevG** [jwarby/jquery-pagewalkthrough#73]
Ex:  Pressing Right arrow key should go to next step. Pressing left arrow key should go to previous step. Pressing Esc should exit the walkthrough, etc.

**Comment by jwarby** [comment]
Hi @NamdhevG, I think this is something that should be handled by consumers instead of baking it into the plugin - ie, you could do something like the following in your application code:

```javascript
document.addEventListener('keyup', e => {
  if (e.which === 39) {
    $.pagewalkthrough('next')
  } else if (e.which === 37) {
    $.pagewalkthrough('prev')
  }
  /* etc */
})
```
